version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zebra-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/zebra_db?serverVersion=8.0"
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.0
    container_name: zebra-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zebra_db
    ports:
      - "3306:3306"
    volumes:
      - zebra-db-data:/var/lib/mysql

volumes:
  zebra-db-data: